//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.15 at 10:35:41 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://trng.imcs.xsd/customer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package trng.imcs.jaxb;
